### ISSUE TITLE
Secureframe/Github issue sync: body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/secureframe-issue-sync#4]
Example:

```
2023/05/18 20:38:02 creating github issue: CQ-NET-3-24: Log sinks configured (GCP)
2023/05/18 20:38:03 create: POST https://api.github.com/repos/chainguard-dev/internal/issues: 422 Validation Failed [{Resource:Issue Field:body Code:custom Message:body is too long} {Resource:Issue Field:body Code:custom Message:body is too long (maximum is 65536 characters)}]
panic: create: POST https://api.github.com/repos/chainguard-dev/internal/issues: 422 Validation Failed [{Resource:Issue Field:body Code:custom Message:body is too long} {Resource:Issue Field:body Code:custom Message:body is too long (maximum is 65536 characters)}]
goroutine 1 [running]:
log.Panicf({0x7c2c3b?, 0x27?}, {0xc00013daa8?, 0x609ff?, 0xc0009bd780?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/log/log.go:392 +0x67
main.main()
	/home/runner/work/internal/internal/secureframe-issue-sync/main.go:147 +0x172a
```

**Comment by tstromberg** [comment]
Fixed by https://github.com/chainguard-dev/secureframe-issue-sync/commit/0f1dc48ff6390b23ee708fbd1dd18a5467777b85
