### ISSUE TITLE
get company test v2s: query: unexpected status code: 400

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/secureframe-issue-sync#8]
The private secureframe API we were using changed again last fall, probably in the run up to their public API release:

```
2024/01/19 13:05:15 Getting Secureframe tests for soc2_alpha ...
2024/01/[19](https://github.com/chainguard-dev/internal/actions/runs/7584163671/job/20657262515#step:4:20) 13:05:16 unexpected status code: 500 (will retry)
[20](https://github.com/chainguard-dev/internal/actions/runs/7584163671/job/20657262515#step:4:21)24/01/19 13:05:18 Secureframe test query failed: get company test v2s: query: unexpected status code: 400
panic: Secureframe test query failed: get company test v2s: query: unexpected status code: 400

goroutine 1 [running]:
log.Panicf({0x7f33d4?, 0xb20dc0?}, {0xc0001a3750?, 0x24?, 0xc00002[21](https://github.com/chainguard-dev/internal/actions/runs/7584163671/job/20657262515#step:4:22)c2?})
	/opt/hostedtoolcache/go/1.21.6/x64/src/log/log.go:439 +0x65
main.main()
	/home/runner/work/internal/internal/secureframe-issue-sync/main.go:61 +0x2c5
exit status 2
```

I've reached out to my contacts at Secureframe to see if this can be transitioned to the public API or if we'll have to reverse-engineer the change again.

**Comment by tstromberg** [comment]
fixed by 295468022cef269c4d8b1473ab60f0166e9a3ab0
